spring.application.name=facturacion


# Configuración para MySQL (Usa variables de entorno del servidor por seguridad)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/facturacion_prod}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-className=com.mysql.cj.jdbc.Driver

# En producción NO se usa ddl-auto=update por riesgo a perder datos. Se usa 'validate' o herramientas como Flyway/Liquibase
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Configuración adicional recomendada para MySQL en Spring Boot
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect